server:
  port: 80
  servlet:
    context-path: /union
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/union?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
#  resources:
#    static-locations: file:C:\Users\Administrator\Pictures\java图库
#  mvc:
#    static-path-pattern: /images/**

mybatis:
  type-aliases-package: com.dong.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


